---
- homebrew:
    update_homebrew: yes

- name: Install fish
  homebrew:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - name: fish

- lineinfile:
    path: /etc/shells
    line: /usr/local/bin/fish
  become: true
  become_user: root

- name: Configure fish
  template:
    src: config.fish.j2
    dest: "/Users/{{ ansible_ssh_user }}/.config/fish/config.fish"
    mode: "0644"

- name: Setup fish as default shell (not work)
  user:
    name: "{{ ansible_ssh_user }}"
    shell: /usr/local/bin/fish

- name: Install oh-my-fish
  shell: |
    curl -L https://get.oh-my.fish > /tmp/install
    fish /tmp/install --noninteractive --yes

- name: Update oh-my-fish
  shell: omf update

- name: Install omf plugins
  shell: "omf install {{ item }}"
  with_items:
    - weather

- name: Install font tap
  homebrew_tap:
    name: caskroom/fonts
    state: present

- name: Install font "Knack Nerd"
  homebrew_cask:
    name: font-hack-nerd-font
    state: present

- name: Install omf theme bobthefish
  shell: |
    omf install bobthefish
    set -g theme_nerd_fonts yes
