---
- homebrew:
    name: nvm
    state: latest

- file:
    path: ~/.nvm
    state: directory
    mode: 0755

- shell: ln -s (brew --prefix nvm)/nvm.sh ~/.nvm/nvm.sh
  args:
    creates: ~/.nvm/nvm.sh
    executable: /usr/local/bin/fish

- git:
    repo: git://github.com/passcod/nvm-fish-wrapper.git
    dest: ~/.config/fish/nvm-wrapper

- blockinfile:
    path: ~/.config/fish/config.fish
    marker: "# {mark} NVM setting"
    content: |
      set -x NVM_DIR ~/.nvm
      source ~/.config/fish/nvm-wrapper/nvm.fish
