---
- pip:
    name: wakatime
    executable: pip3

- name: Configure
  template:
    src: wakatime.cfg.j2
    dest: "/Users/{{ ansible_ssh_user }}/.wakatime.cfg"

- get_url:
    url: https://raw.githubusercontent.com/Cyber-Duck/fish-wakatime/master/fish-wakatime.sh
    dest: ~/.config/fish/functions/fish_prompt.fish
