---
- pip:
    name: wakatime
    executable: pip3

- lineinfile:
    path: ~/.wakatime.cfg
    line: "{{ lookup('env','WAKATIME_API_KEY') }}"
    create: yes

- get_url:
    url: https://raw.githubusercontent.com/Cyber-Duck/fish-wakatime/master/fish-wakatime.sh
    dest: ~/.config/fish/functions/fish_prompt.fish
