---
- homebrew:
    update_homebrew: yes

- homebrew:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - name: ack
    - name: entr
    - name: git
    - name: git-flow
    - name: go
    - name: heroku
    - name: jq
    - name: mercurial
    - name: npm
    - name: nvm
    - name: pgcli
    - name: postgresql
    - name: pstree
    - name: python3
    - name: shellcheck
    - name: sqlite
    - name: terraform
    - name: tig
    - name: tree
    - name: vim
    - name: watchman
    - name: wget
    - name: youtube-dl

- homebrew_cask:
    name: "{{ item.name }}"
    state: present
  with_items:
    - name: calibre
    - name: controlplane
    - name: dash
    - name: dropbox
    - name: firefox
    - name: google-backup-and-sync
    - name: google-chrome
    - name: google-cloud-sdk
    - name: insomnia
    - name: istat-menus
    - name: iterm2
    - name: opera
    - name: pycharm
    - name: rescuetime
    - name: spectacle
    - name: ssh-tunnel-manager
    - name: vivaldi
    - name: webstorm
    - name: welly
    - name: xmind
