- name: Creates ~/bin directory
  file:
    path: "/Users/{{ ansible_ssh_user }}/bin"
    state: directory

- template:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/bin/{{ item | basename | regex_replace('.j2','') }}"
    mode: "0755"
  with_fileglob:
    - files/*
